version: "3"

services:
  postgres:
    container_name: gobarber_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "gobarber"
      POSTGRES_PASSWORD: "gobarber"
      POSTGRES_DB: "gobarber"
